### ISSUE TITLE
bug: AzVolume controller panic with incomplete objects

### ISSUE THREAD

**Issue by edreed** [abhisheksinghbaghel/azuredisk-csi-driver#46]
**What happened**:

I had some left over AzVolume definitions from a previous build that were missing some of the new fields. In the absence of this fields, the controller panics. We should figure out if it is possible to create AzVolume instances with missing fields and if so handle this condition gracefully.

**What you expected to happen**:

No panics.

**How to reproduce it**:

**Anything else we need to know?**:

Log showing stack trace of the panic:

```console
E0504 00:05:08.580075       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 371 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1996de0, 0x297e210)
        /home/edreed/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /home/edreed/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x86
panic(0x1996de0, 0x297e210)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
sigs.k8s.io/azuredisk-csi-driver/pkg/provisioner.(*CloudProvisioner).validateCreateVolumeRequestParams(0xc000186078, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xed81d78d6)
        /home/edreed/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/provisioner/cloudprovisioner.go:746 +0x3a
sigs.k8s.io/azuredisk-csi-driver/pkg/provisioner.(*CloudProvisioner).CreateVolume(0xc000186078, 0x1e3b6f8, 0xc0003817a0, 0xc0004304d3, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/edreed/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/provisioner/cloudprovisioner.go:85 +0x85
sigs.k8s.io/azuredisk-csi-driver/pkg/controller.(*reconcileAzVolume).createVolume(0xc000a5ee00, 0x1e3b6f8, 0xc0003817a0, 0xc000a6b680, 0xd, 0x0, 0x0)
        /home/edreed/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/controller/azvolume.go:201 +0xe3
sigs.k8s.io/azuredisk-csi-driver/pkg/controller.(*reconcileAzVolume).triggerCreate(0xc000a5ee00, 0x1e3b6f8, 0xc0003817a0, 0xc000430490, 0xd, 0xc000430490, 0xd)
        /home/edreed/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/controller/azvolume.go:122 +0x2de
sigs.k8s.io/azuredisk-csi-driver/pkg/controller.(*reconcileAzVolume).Reconcile(0xc000a5ee00, 0x1e3b6f8, 0xc0003817a0, 0xc0004304b0, 0xe, 0xc000430490, 0xd, 0xc0003817a0, 0xc0004a8000, 0x1a5ab40, ...)
        /home/edreed/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/controller/azvolume.go:67 +0x4ce
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000ba1680, 0x1e3b650, 0xc000a5eec0, 0x1a0cba0, 0xc000918ba0)
        /home/edreed/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:297 +0x30d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000ba1680, 0x1e3b650, 0xc000a5eec0, 0x0)
        /home/edreed/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:252 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2(0x1e3b650, 0xc000a5eec0)
        /home/edreed/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
        /home/edreed/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0005c7f50)
        /home/edreed/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000a23f50, 0x1e06520, 0xc000381710, 0xc000a5ee01, 0xc000bca7e0)
        /home/edreed/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0005c7f50, 0x3b9aca00, 0x0, 0x1, 0xc000bca7e0)
        /home/edreed/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x1e3b650, 0xc000a5eec0, 0xc00046ee80, 0x3b9aca00, 0x0, 0x1)
        /home/edreed/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x1e3b650, 0xc000a5eec0, 0xc00046ee80, 0x3b9aca00)
        /home/edreed/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        /home/edreed/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:212 +0x40d
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x17c46fa]
```

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by edreed** [comment]
I seem to have some old `AzVolume` instances left over from a previous run without all of the new fields. It seems this was the resource for the `nil` capacity range.

**Comment by edreed** [comment]
The panic was caused by missing fields in the old `AzVolume` definition. Needs to see if its still possible to create these conditions and crash the controller.
